name: blueprint
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.6

dependencies:
  app_ui:
    path: ./packages/app_ui
  authentication_repository:
    path: ./packages/authentication_repository
  auto_route: ^7.8.3
  bloc: ^8.1.1
  blueprint_repository:
    path: ./packages/blueprint_repository
  cached_network_image: ^3.2.3
  calendar_repository:
    path: ./packages/calendar_repository
  cloud_firestore: ^4.10.0
  cloud_functions: ^4.5.0
  collapsible_sidebar: ^2.0.3+3
  collection: ^1.17.0
  dynamic_color: ^1.6.3
  firebase_auth: ^4.11.0
  firebase_core: ^2.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_secure_storage: ^8.0.0
  flutter_web_auth: ^0.5.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.5
  hydrated_bloc: ^9.1.0
  injectable: ^2.1.1
  integrations_repository:
    path: ./packages/integrations_repository
  intl: ^0.18.0
  jiffy: ^5.0.0
  json_annotation: ^4.8.0
  markdown: ^7.1.1
  meta: ^1.9.1
  path_provider: ^2.0.14
  share_plus: ^7.1.0
  sidebarx: ^0.15.0
  stream_transform: ^2.1.0
  syncfusion_flutter_calendar: ^21.1.38
  task_repository:
    path: ./packages/task_repository
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  assets:
    - assets/docs/img/
  uses-material-design: true
  generate: true
