name: blueprint
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: 3.10.0

dependencies:
  authentication_repository:
    path: ./packages/authentication_repository
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  collapsible_sidebar: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  github_repository:
    path: ./packages/platforms_integrations/github_repository
  intl: ^0.18.0
  jira_repository:
    path: ./packages/platforms_integrations/jira_repository
  integrations_repository:
    path: ./packages/integrations_repository
  jiffy: ^5.0.0
  json_annotation: ^4.8.0
  sidebarx: ^0.15.0
  url_launcher: ^6.1.10
  flutter_secure_storage: ^8.0.0
  syncfusion_flutter_calendar: ^21.1.38
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.14
  collection: ^1.17.0
  google_fonts: ^4.0.3
  dynamic_color: ^1.6.3
  auto_route: ^6.2.1
  firebase_core: ^2.11.0
  injectable: ^2.1.1
  firebase_auth: ^4.5.0
  get_it: ^7.6.0

dev_dependencies:
  auto_route_generator: ^6.2.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  assets:
    - assets/docs/img/
  uses-material-design: true
  generate: true
