name: google_calendar_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  calendar_repository:
    path: ../calendar_repository
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  googleapis: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
