name: firebase_dev_access
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cloud_firestore: ^4.13.2
  cloud_functions: ^4.5.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
