name: platforms_api_client
description: A client for managing the platforms
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.6

dependencies:
  async: ^2.10.0
  cloud_firestore: ^4.7.1
  collection: ^1.17.0
  fake_cloud_firestore: ^2.4.1+1
  flutter:
    sdk: flutter
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
