name: authentication_repository
description: An authentication interface implemented with firebase authentication service.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: 3.3.10

dependencies:
  crypto: ^3.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.1.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: 4.4.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.2.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
