name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  dynamic_color: ^1.6.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.3
  jiffy: ^6.2.1
  syncfusion_flutter_calendar: ^23.1.44


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner:
  flutter_gen_runner:
  very_good_analysis: ^5.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/logo/logo_dark.svg
    - assets/logo/logo_light.svg
  uses-material-design: true
