name: local_platform_integration_repository
description: A repository for fetching platform integration data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.6
  very_good_analysis: ^3.1.0
