name: event_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.3.0

dependencies:
  async: ^2.10.0
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.3.1
  collection: ^1.17.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  integrations_repository:
    path: ../integrations_repository
  json_annotation: ^4.8.1
  stream_transform: ^2.1.0

dev_dependencies:
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
