name: blueprint_repository

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/blueprint_repository/**"
      - ".github/workflows/blueprint_repository.yaml"
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.13.6
      flutter_channel: stable
      working_directory: packages/blueprint_repository
      min_coverage: 0
